### ISSUE TITLE
Start bot polling - why async?

### ISSUE THREAD

**Issue by Olegt0rr** [darksidecat/aiogram-multibot-example#2]
Why this method is async?

https://github.com/darksidecat/aiogram-multibot-example/blob/9608061caf792a26db87a1fee4eee3b8b5e5346a/polling_manager.py#L19-L42

**Comment by darksidecat** [comment]
Closed by https://github.com/darksidecat/aiogram-multibot-example/commit/4bc83fb9b3cfb5815035bd335a646c40919010a7
