### ISSUE TITLE
aiogram\dispatcher\dispatcher.py

### ISSUE THREAD

**Issue by ivan-bryliant** [darksidecat/aiogram-multibot-example#4]
error:   File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 52, in __init__
    super(Dispatcher, self).__init__(**kwargs)
TypeError: Router.__init__() got an unexpected keyword argument 'isolate_events'

aiogram 3.0.0b
python 3.10.3

**Comment by darksidecat** [comment]
Fixed in https://github.com/darksidecat/aiogram-multibot-example/commit/cb21b0bcfe6e8ce6649b14724aaf8ca1ab08591a

Please let me know if the problem is gone

**Comment by ivan-bryliant** [comment]
yes it works thank you very much!🙌
